// auto-generated by scripts/extract-agent-timeline.mjs
// DO NOT EDIT — re-run the script to update
// Source: docs/meetings/ in OpenProfile repo
// Generated: 2026-03-11

export interface MeetingEvent {
  date: string;   // YYYY-MM-DD
  title: string;
  file: string;   // meeting file basename (without .md)
  type: 'meeting' | 'planning' | 'retrospective' | 'kickoff' | 'brainstorm' | 'all-hands' | 'research';
}

export const AGENT_MEETINGS: Record<string, MeetingEvent[]> = {
  "brain": [
    {
      "date": "2026-03-11",
      "title": "全体会议 #01 — Pixel Agents 与 AI-Native 数字社区构想",
      "file": "2026-03-11-01-pixel-agents-all-hands",
      "type": "all-hands"
    },
    {
      "date": "2026-03-11",
      "title": "会议纪要：v5.x 系列总结 + v6.0.0 方向规划会",
      "file": "2026-03-11-02-v5x-retro-v6-planning",
      "type": "retrospective"
    },
    {
      "date": "2026-03-11",
      "title": "专题研讨会 — Agent 可视化技术方向专项讨论",
      "file": "2026-03-11-03-agent-visualization-tech-seminar",
      "type": "meeting"
    },
    {
      "date": "2026-03-11",
      "title": "全体深度反思会 #09 — 转折点：我们到底需要什么",
      "file": "2026-03-11-04-turning-point-strategic-reflection",
      "type": "all-hands"
    },
    {
      "date": "2026-03-10",
      "title": "会议纪要：团队演进机制研究会",
      "file": "2026-03-10-01-team-evolution-research",
      "type": "research"
    },
    {
      "date": "2026-03-10",
      "title": "全体会议 #06 — 资产全量审计 + 自由发言深度讨论",
      "file": "2026-03-10-06-all-hands-asset-audit-free-discussion",
      "type": "all-hands"
    },
    {
      "date": "2026-03-10",
      "title": "团队资产全面优化讨论会",
      "file": "2026-03-10-07-comprehensive-asset-optimization",
      "type": "meeting"
    },
    {
      "date": "2026-03-01",
      "title": "会议纪要：v4→v5 里程碑复盘 + v5.0~v5.5 路线畅想会",
      "file": "2026-03-01-02-v5-milestone-review-and-roadmap",
      "type": "retrospective"
    }
  ],
  "pm": [
    {
      "date": "2026-03-11",
      "title": "全体会议 #01 — Pixel Agents 与 AI-Native 数字社区构想",
      "file": "2026-03-11-01-pixel-agents-all-hands",
      "type": "all-hands"
    },
    {
      "date": "2026-03-11",
      "title": "会议纪要：v5.x 系列总结 + v6.0.0 方向规划会",
      "file": "2026-03-11-02-v5x-retro-v6-planning",
      "type": "retrospective"
    },
    {
      "date": "2026-03-11",
      "title": "专题研讨会 — Agent 可视化技术方向专项讨论",
      "file": "2026-03-11-03-agent-visualization-tech-seminar",
      "type": "meeting"
    },
    {
      "date": "2026-03-11",
      "title": "全体深度反思会 #09 — 转折点：我们到底需要什么",
      "file": "2026-03-11-04-turning-point-strategic-reflection",
      "type": "all-hands"
    },
    {
      "date": "2026-03-10",
      "title": "会议纪要：团队演进机制研究会",
      "file": "2026-03-10-01-team-evolution-research",
      "type": "research"
    },
    {
      "date": "2026-03-10",
      "title": "全体会议 #06 — 资产全量审计 + 自由发言深度讨论",
      "file": "2026-03-10-06-all-hands-asset-audit-free-discussion",
      "type": "all-hands"
    },
    {
      "date": "2026-03-10",
      "title": "工具层 Skills 脚手架全体会议",
      "file": "2026-03-10-09-skills-scaffold-all-hands",
      "type": "all-hands"
    },
    {
      "date": "2026-03-01",
      "title": "会议纪要：v4→v5 里程碑复盘 + v5.0~v5.5 路线畅想会",
      "file": "2026-03-01-02-v5-milestone-review-and-roadmap",
      "type": "retrospective"
    }
  ],
  "dev": [
    {
      "date": "2026-03-11",
      "title": "全体会议 #01 — Pixel Agents 与 AI-Native 数字社区构想",
      "file": "2026-03-11-01-pixel-agents-all-hands",
      "type": "all-hands"
    },
    {
      "date": "2026-03-11",
      "title": "会议纪要：v5.x 系列总结 + v6.0.0 方向规划会",
      "file": "2026-03-11-02-v5x-retro-v6-planning",
      "type": "retrospective"
    },
    {
      "date": "2026-03-11",
      "title": "专题研讨会 — Agent 可视化技术方向专项讨论",
      "file": "2026-03-11-03-agent-visualization-tech-seminar",
      "type": "meeting"
    },
    {
      "date": "2026-03-11",
      "title": "团队内部讨论 — Agent Persona Layer 两项技术决策",
      "file": "2026-03-11-04-tech-decision-internal-discussion",
      "type": "meeting"
    },
    {
      "date": "2026-03-11",
      "title": "全体深度反思会 #09 — 转折点：我们到底需要什么",
      "file": "2026-03-11-04-turning-point-strategic-reflection",
      "type": "all-hands"
    },
    {
      "date": "2026-03-10",
      "title": "会议纪要：团队演进机制研究会",
      "file": "2026-03-10-01-team-evolution-research",
      "type": "research"
    },
    {
      "date": "2026-03-10",
      "title": "全体会议 #06 — 资产全量审计 + 自由发言深度讨论",
      "file": "2026-03-10-06-all-hands-asset-audit-free-discussion",
      "type": "all-hands"
    },
    {
      "date": "2026-03-01",
      "title": "会议纪要：v4→v5 里程碑复盘 + v5.0~v5.5 路线畅想会",
      "file": "2026-03-01-02-v5-milestone-review-and-roadmap",
      "type": "retrospective"
    },
    {
      "date": "2026-02-25",
      "title": "团队会议纪要 #001 — 项目架构启动会",
      "file": "2026-02-25-kickoff",
      "type": "kickoff"
    }
  ],
  "researcher": [
    {
      "date": "2026-03-11",
      "title": "全体会议 #01 — Pixel Agents 与 AI-Native 数字社区构想",
      "file": "2026-03-11-01-pixel-agents-all-hands",
      "type": "all-hands"
    },
    {
      "date": "2026-03-11",
      "title": "会议纪要：v5.x 系列总结 + v6.0.0 方向规划会",
      "file": "2026-03-11-02-v5x-retro-v6-planning",
      "type": "retrospective"
    },
    {
      "date": "2026-03-11",
      "title": "专题研讨会 — Agent 可视化技术方向专项讨论",
      "file": "2026-03-11-03-agent-visualization-tech-seminar",
      "type": "meeting"
    },
    {
      "date": "2026-03-11",
      "title": "全体深度反思会 #09 — 转折点：我们到底需要什么",
      "file": "2026-03-11-04-turning-point-strategic-reflection",
      "type": "all-hands"
    },
    {
      "date": "2026-03-10",
      "title": "会议纪要：团队演进机制研究会",
      "file": "2026-03-10-01-team-evolution-research",
      "type": "research"
    },
    {
      "date": "2026-03-10",
      "title": "全体会议 #06 — 资产全量审计 + 自由发言深度讨论",
      "file": "2026-03-10-06-all-hands-asset-audit-free-discussion",
      "type": "all-hands"
    },
    {
      "date": "2026-03-01",
      "title": "会议纪要：v4→v5 里程碑复盘 + v5.0~v5.5 路线畅想会",
      "file": "2026-03-01-02-v5-milestone-review-and-roadmap",
      "type": "retrospective"
    },
    {
      "date": "2026-02-25",
      "title": "团队会议纪要 #001 — 项目架构启动会",
      "file": "2026-02-25-kickoff",
      "type": "kickoff"
    }
  ],
  "code-reviewer": [
    {
      "date": "2026-03-11",
      "title": "全体会议 #01 — Pixel Agents 与 AI-Native 数字社区构想",
      "file": "2026-03-11-01-pixel-agents-all-hands",
      "type": "all-hands"
    },
    {
      "date": "2026-03-11",
      "title": "会议纪要：v5.x 系列总结 + v6.0.0 方向规划会",
      "file": "2026-03-11-02-v5x-retro-v6-planning",
      "type": "retrospective"
    },
    {
      "date": "2026-03-11",
      "title": "专题研讨会 — Agent 可视化技术方向专项讨论",
      "file": "2026-03-11-03-agent-visualization-tech-seminar",
      "type": "meeting"
    },
    {
      "date": "2026-03-11",
      "title": "全体深度反思会 #09 — 转折点：我们到底需要什么",
      "file": "2026-03-11-04-turning-point-strategic-reflection",
      "type": "all-hands"
    },
    {
      "date": "2026-03-10",
      "title": "会议纪要：团队演进机制研究会",
      "file": "2026-03-10-01-team-evolution-research",
      "type": "research"
    },
    {
      "date": "2026-03-10",
      "title": "全体会议 #06 — 资产全量审计 + 自由发言深度讨论",
      "file": "2026-03-10-06-all-hands-asset-audit-free-discussion",
      "type": "all-hands"
    },
    {
      "date": "2026-03-01",
      "title": "会议纪要：v4→v5 里程碑复盘 + v5.0~v5.5 路线畅想会",
      "file": "2026-03-01-02-v5-milestone-review-and-roadmap",
      "type": "retrospective"
    },
    {
      "date": "2026-02-25",
      "title": "团队会议纪要 #001 — 项目架构启动会",
      "file": "2026-02-25-kickoff",
      "type": "kickoff"
    }
  ],
  "profile-designer": [
    {
      "date": "2026-03-11",
      "title": "全体会议 #01 — Pixel Agents 与 AI-Native 数字社区构想",
      "file": "2026-03-11-01-pixel-agents-all-hands",
      "type": "all-hands"
    },
    {
      "date": "2026-03-11",
      "title": "会议纪要：v5.x 系列总结 + v6.0.0 方向规划会",
      "file": "2026-03-11-02-v5x-retro-v6-planning",
      "type": "retrospective"
    },
    {
      "date": "2026-03-11",
      "title": "专题研讨会 — Agent 可视化技术方向专项讨论",
      "file": "2026-03-11-03-agent-visualization-tech-seminar",
      "type": "meeting"
    },
    {
      "date": "2026-03-11",
      "title": "全体深度反思会 #09 — 转折点：我们到底需要什么",
      "file": "2026-03-11-04-turning-point-strategic-reflection",
      "type": "all-hands"
    },
    {
      "date": "2026-03-10",
      "title": "会议纪要：团队演进机制研究会",
      "file": "2026-03-10-01-team-evolution-research",
      "type": "research"
    },
    {
      "date": "2026-03-10",
      "title": "全体会议 #06 — 资产全量审计 + 自由发言深度讨论",
      "file": "2026-03-10-06-all-hands-asset-audit-free-discussion",
      "type": "all-hands"
    },
    {
      "date": "2026-03-01",
      "title": "会议纪要：v4→v5 里程碑复盘 + v5.0~v5.5 路线畅想会",
      "file": "2026-03-01-02-v5-milestone-review-and-roadmap",
      "type": "retrospective"
    },
    {
      "date": "2026-02-25",
      "title": "团队会议纪要 #001 — 项目架构启动会",
      "file": "2026-02-25-kickoff",
      "type": "kickoff"
    }
  ],
  "brand": [
    {
      "date": "2026-03-11",
      "title": "全体会议 #01 — Pixel Agents 与 AI-Native 数字社区构想",
      "file": "2026-03-11-01-pixel-agents-all-hands",
      "type": "all-hands"
    },
    {
      "date": "2026-03-11",
      "title": "会议纪要：v5.x 系列总结 + v6.0.0 方向规划会",
      "file": "2026-03-11-02-v5x-retro-v6-planning",
      "type": "retrospective"
    },
    {
      "date": "2026-03-11",
      "title": "专题研讨会 — Agent 可视化技术方向专项讨论",
      "file": "2026-03-11-03-agent-visualization-tech-seminar",
      "type": "meeting"
    },
    {
      "date": "2026-03-11",
      "title": "全体深度反思会 #09 — 转折点：我们到底需要什么",
      "file": "2026-03-11-04-turning-point-strategic-reflection",
      "type": "all-hands"
    },
    {
      "date": "2026-03-10",
      "title": "会议纪要：团队演进机制研究会",
      "file": "2026-03-10-01-team-evolution-research",
      "type": "research"
    },
    {
      "date": "2026-03-10",
      "title": "全体会议 #06 — 资产全量审计 + 自由发言深度讨论",
      "file": "2026-03-10-06-all-hands-asset-audit-free-discussion",
      "type": "all-hands"
    },
    {
      "date": "2026-03-01",
      "title": "会议纪要：v4→v5 里程碑复盘 + v5.0~v5.5 路线畅想会",
      "file": "2026-03-01-02-v5-milestone-review-and-roadmap",
      "type": "retrospective"
    }
  ]
};

/** 各 Agent 参会总数 */
export const MEETING_COUNTS: Record<string, number> = {
  "brain": 8,
  "pm": 8,
  "dev": 9,
  "researcher": 8,
  "code-reviewer": 8,
  "profile-designer": 8,
  "brand": 7,
};
